In [142]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('Downloads/titanic.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [143]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [144]:
# as male is a string and wont fit in linear regresion soo we have to convert iit into int or float
import numpy as np
df['numeric_sex'] = np.where(df['Sex'] == 'male',1,0)

In [145]:
# droping unwanted columns
df = df.drop(['PassengerId','Cabin','Ticket','Embarked','SibSp','Parch','Name','Sex'],axis = 1)
print(df)

     Survived  Pclass   Age      Fare  numeric_sex
0           0       3  34.5    7.8292            1
1           1       3  47.0    7.0000            0
2           0       2  62.0    9.6875            1
3           0       3  27.0    8.6625            1
4           1       3  22.0   12.2875            0
..        ...     ...   ...       ...          ...
413         0       3   NaN    8.0500            1
414         1       1  39.0  108.9000            0
415         0       3  38.5    7.2500            1
416         0       3   NaN    8.0500            1
417         0       3   NaN   22.3583            1

[418 rows x 5 columns]

In [146]:
df = df.dropna()

In [147]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [148]:
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)
x_train
x_test

array([[-0.23745874,  0.20175375, -0.51058455,  0.69156407],
       [-1.39082974, -0.63820062,  1.16435982,  0.69156407],
       [ 0.91591227, -0.00823485, -0.59933699,  0.69156407],
       [ 0.91591227, -0.91818541, -0.44057951, -1.44599761],
       [-1.39082974,  1.4616853 ,  0.92407393,  0.69156407],
       [ 0.91591227, -0.35821583, -0.58669493,  0.69156407],
       [ 0.91591227, -0.56820443, -0.60552902, -1.44599761],
       [ 0.91591227, -0.21822344, -0.31089155,  0.69156407],
       [ 0.91591227, -0.56820443, -0.60501302,  0.69156407],
       [ 0.91591227, -0.49820823, -0.60458371,  0.69156407],
       [-0.23745874, -0.56820443, -0.19332965, -1.44599761],
       [-1.39082974,  0.97171192,  0.86920634,  0.69156407],
       [-0.23745874, -0.91818541, -0.54876874,  0.69156407],
       [-0.23745874, -0.14822724, -0.49716848,  0.69156407],
       [ 0.91591227, -0.77819302, -0.26703133,  0.69156407],
       [ 0.91591227,  0.58673283, -0.45382427,  0.69156407],
       [-0.23745874, -0.84818922, -0.22884714, -1.44599761],
       [-1.39082974,  0.90171572,  0.54223202, -1.44599761],
       [-1.39082974,  1.11170431,  0.86920634, -1.44599761],
       [ 0.91591227, -0.77819302, -0.61636508,  0.69156407],
       [ 0.91591227, -1.61814739, -0.45081494, -1.44599761],
       [-1.39082974,  1.95165868,  0.80917873, -1.44599761],
       [ 0.91591227,  0.44674044, -0.61584908,  0.69156407],
       [-1.39082974,  0.27174994,  0.78750662,  0.69156407],
       [ 0.91591227, -1.4431569 , -0.46620833,  0.69156407],
       [-0.23745874, -0.77819302, -0.33204766, -1.44599761],
       [ 0.91591227, -0.77819302, -0.60501302,  0.69156407],
       [-1.39082974, -0.49820823,  0.37883258, -1.44599761],
       [-1.39082974,  2.23164347,  0.78767793,  0.69156407],
       [ 0.91591227,  0.02676325, -0.56940884,  0.69156407],
       [-0.23745874,  1.74167009, -0.49716848,  0.69156407],
       [ 0.91591227, -0.98818161, -0.58669493,  0.69156407],
       [ 0.91591227,  0.06176135, -0.60337833,  0.69156407],
       [-1.39082974,  1.95165868,  4.66285729, -1.44599761]])

In [149]:
x = df.iloc[:,1:]
y =  df.iloc[:,0]
x

     Pclass   Age      Fare  numeric_sex
0         3  34.5    7.8292            1
1         3  47.0    7.0000            0
2         2  62.0    9.6875            1
3         3  27.0    8.6625            1
4         3  22.0   12.2875            0
..      ...   ...       ...          ...
409       3   3.0   13.7750            0
411       1  37.0   90.0000            0
412       3  28.0    7.7750            0
414       1  39.0  108.9000            0
415       3  38.5    7.2500            1

[331 rows x 4 columns]

In [150]:
y

0      0
1      1
2      0
3      0
4      1
      ..
409    1
411    1
412    1
414    1
415    0
Name: Survived, Length: 331, dtype: int64

In [151]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 331 entries, 0 to 415
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Survived     331 non-null    int64
 1   Pclass       331 non-null    int64
 2   Age          331 non-null    float64
 3   Fare         331 non-null    float64
 4   numeric_sex  331 non-null    int64
dtypes: float64(2), int64(3)
memory usage: 15.5 KB

In [152]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.1)

In [153]:
x_train

     Pclass   Age      Fare  numeric_sex
326       2  12.0   39.0000            0
120       2  12.0   15.7500            0
306       1  30.0  151.5500            1
337       3  39.0    7.2292            1
343       1  58.0  512.3292            0
..      ...   ...       ...          ...
16        2  35.0   12.3500            1
320       3  26.0    7.7750            1
308       1  55.0   93.5000            1
264       2  30.0   12.7375            1
97        3  29.0    7.9250            1

[297 rows x 4 columns]

In [154]:
from sklearn.linear_model import LinearRegression
ft = LinearRegression()
ft.fit(x_train,y_train)

LinearRegression()

In [155]:
predict = ft.predict(x_test) 
predict

array([-2.22044605e-16,  1.00000000e+00, -2.22044605e-16, -2.22044605e-16,
        1.00000000e+00, -2.22044605e-16,  1.00000000e+00, -2.22044605e-16,
        0.00000000e+00, -2.22044605e-16, -2.22044605e-16,  0.00000000e+00,
        1.00000000e+00, -2.22044605e-16, -2.22044605e-16,  1.00000000e+00,
       -2.22044605e-16, -2.22044605e-16, -2.22044605e-16,  1.00000000e+00,
        1.00000000e+00, -2.22044605e-16, -2.22044605e-16,  1.00000000e+00,
        1.00000000e+00, -2.22044605e-16, -2.22044605e-16,  1.00000000e+00,
       -2.22044605e-16, -2.22044605e-16, -2.22044605e-16, -2.22044605e-16,
       -2.22044605e-16, -2.22044605e-16])

In [156]:
y_test

57     0
314    1
393    0
55     0
79     1
373    0
48     1
351    0
234    0
348    0
381    0
407    0
117    1
145    0
180    0
119    1
329    0
340    0
115    0
356    1
182    1
95     0
149    0
283    1
385    1
60     0
201    0
112    1
321    0
38     0
195    0
404    0
128    0
223    0
Name: Survived, dtype: int64