| Parameter | Purpose | Typical Values |
| --- | --- | --- |
| ``n_estimators`` | Number of trees | 100–500 |
| ``max_depth`` | Maximum depth of each tree | 3–10 |
| ``learning_rate`` | Shrinkage factor (step size) | 0.01–0.3 |
| ``objective`` | Defines task type | ``"reg:squarederror"`` (regression), ``"binary:logistic"`` (binary classification), ``"multi:softmax"`` (multi-class) |
| ``num_class`` | Needed only for multi-class classification | Number of classes |

In [26]:
import pandas as pd
from sklearn.datasets import fetch_california_housing

df = fetch_california_housing(as_frame=True)
data = df.frame
data

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [34]:
from xgboost import XGBRegressor

model = XGBRegressor(n_estimators = 200,
                        max_depth=6,
                        learning_rate=0.1,
                        objective="reg:squarederror")

In [35]:
from sklearn.model_selection import train_test_split
X = data.iloc[:,:-1]
y = data.iloc[:,-1]
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42,test_size=0.2)

In [36]:
model.fit(X_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=200,
             n_jobs=None, num_parallel_tree=None, ...)

In [39]:
pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,pred)

0.835795246184819

In [42]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

# Predict
y_pred = model.predict(X_test)

# Evaluate
print("R²:", r2_score(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("MAE:", mean_absolute_error(y_test, y_pred))

R²: 0.835795246184819
RMSE: 0.4638700072964944
MAE: 0.3026459157770641

## For Classification

In [95]:
dataset = pd.read_csv(r"C:\Users\pc\Downloads\covid_toy.csv",)
dataset

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [104]:
# Convert all object columns in dataset to category
for col in dataset.select_dtypes(include="object").columns:
    dataset[col] = dataset[col].astype("category")

print(dataset.dtypes)  # confirm no 'object' left

dataset['has_covid'].replace({'Yes':1,'No':0},inplace=True)

age             int64
gender       category
fever         float64
cough        category
city         category
has_covid       int64
dtype: object

C:\Users\pc\AppData\Local\Temp\ipykernel_5512\1136348096.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['has_covid'].replace({'Yes':1,'No':0},inplace=True)

In [105]:
X = dataset.iloc[:,:-1]
y = dataset.iloc[:,-1]
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42,stratify=y,test_size=0.2)

In [120]:
from xgboost import XGBClassifier
model = XGBClassifier(n_estimators = 600,max_dept = 6,tree_method="hist",learning_rate = 0.3,objective = 'binary:logistic', enable_categorical=True)

In [121]:
model.fit(X_train,y_train)

e:\Anaconda\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:02:53] WARNING: C:\Users\task_177740979073858\croot\xgboost-split_1777409985184\work\src\learner.cc:782:
Parameters: { "max_dept" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.3, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_dept=6,
              max_depth=None, max_leaves=None, min_child_weight=None,
              missing=nan, monotone_constraints=None, multi_strategy=None,
              n_estimators=600, n_jobs=None, ...)

In [122]:
model.predict(X_test)

array([0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1])

In [123]:
from sklearn.metrics import accuracy_score
print("Accuracy:", accuracy_score(y_test, model.predict(X_test)))
from sklearn.metrics import confusion_matrix
print("Confusion Matrix:\n", confusion_matrix(y_test, model.predict(X_test)))
from sklearn.metrics import classification_report
print(classification_report(y_test, model.predict(X_test)))

Accuracy: 0.35
Confusion Matrix:
 [[3 8]
 [5 4]]
              precision    recall  f1-score   support

           0       0.38      0.27      0.32        11
           1       0.33      0.44      0.38         9

    accuracy                           0.35        20
   macro avg       0.35      0.36      0.35        20
weighted avg       0.36      0.35      0.35        20